### ISSUE TITLE
email_id is required for POST /ctms

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#104]
When sending a minimal contact to ``POST /ctms``:

```json
{
  "email": {
    "primary_email": "test-20210315@example.com"
  }
}
```

I get a ``422 Unprocessable Entity``

```json
{
  "detail": [
    {
      "loc": [
        "body",
        "email",
        "email_id"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    }
  ]
}
```

I expected a new contact to be created with a server-generated ``email_id``.

**Comment by imbstack** [comment]
huh, we have tests for this. I must've messed something up pretty severely I guess? I'll look into this now
