### ISSUE TITLE
Update timestamps do not change with updates

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#129]
If a contact is updated via ``PUT /ctms/{email_id}``, then the value of ``email.update_timestamp`` does not change, but remains the original value, often the same as ``email.create_timestamp``.

**Comment by jwhitlock** [comment]
One solution could be a new updates table that is also used for the Acoustic sync (issue #53):

* `email_id` - The email ID for the "contact"
* `update_timestamp` - Set whenever a "contact" is updated across several tables
* `acoustic_timestamp` - Set equal to `update_timestamp` when the data is synced to Acoustic

Per-row updates could be implemented with triggers (or dropped). The `updates.update_timestamp` could also be set via trigger, or set by the app as part of API calls.

**Comment by cvalaas** [comment]
If you wanted to go the trigger route, I have a sample:

CREATE OR REPLACE FUNCTION change_trigger() RETURNS trigger AS $$
    BEGIN
        INSERT INTO acoustic_sync
            (table_name, row_id, updated_in_acoustic)
            VALUES
            (TG_TABLE_NAME, NEW.id, false)
        ON CONFLICT (table_name, row_id, updated_in_acoustic) DO NOTHING;
        RETURN NEW;
    END;
$$ LANGUAGE 'plpgsql' SECURITY DEFINER;

**Comment by cvalaas** [comment]
(That was cut 'n' paste, so not a 1:1 match to your suggestion above)

**Comment by jwhitlock** [comment]
Fixed by @bsieber-mozilla with PR #156
