### ISSUE TITLE
Add `after` to `GET /updates` response JSON, allow empty

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#140]
The user of the `GET /updates` API has two requested changes:

1. Add the `after` parameter to the JSON response, so that the next URL can be constructed from the JSON:

```json
{
  "next": "https://ctms.example.com/updates?start=2021-03-31T20:30:00+00:00&end=2021-03-31T20:45:00+00:00&after=MjAyMS0wMy0zMVQyMDozMToyOC40MzE0MDIrMD&limit=10",
  "start": "2021-03-31T20:30:00+00:00",
  "end": "2021-03-31T20:45:00+00:00",
  "limit": 10,
  "after": "MjAyMS0wMy0zMVQyMDozMToyOC40MzE0MDIrMD",
  "items": [
    {
      ... // CTMS contact JSON
    }, ... // Additional CTMS contact JSON
  ]
}
```

(this was in @bsieber-mozilla's initial PR, I asked him to remove it, so +1 points to beiber)

2. Allow an empty `after` parameter, such as:

https://ctms.example.com/updates?start=2021-03-31T00:00&after=

I'm guessing that all empty parameters, except for `start` should also work:

https://ctms.example.com/updates?start=2021-03-31T00:00&end=&limit=after=

**Comment by bsieber-mozilla** [comment]
I think with the merging of #143 we can close this.
