### ISSUE TITLE
Allow HEAD to ``/__heartbeat__``, ``/__lb_heartbeat__`` endpoints

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#165]
Allow ``HEAD`` as well as ``GET`` requests to [Dockerflow](https://github.com/mozilla-services/Dockerflow) endpoints:

* ``/__heartbeat__``
* ``/__lb_heartbeat__``

A user or service in production is requesting ``HEAD /__heartbeat__``, and getting a 405. It is then trying ``GET /__heartbeart__`` ``HEAD`` makes sense, since the status code of ``200`` is sufficient to determine that the service is healthy.

**Comment by bsieber-mozilla** [comment]
I'm closing this since #205 has been merged in.
