### ISSUE TITLE
Update dependencies with dependabot

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#172]
Dependabot can submit PRs when a Python dependency is updated, with different schedules for regular and security updates. This is useful for a shipped project, but could be a distraction with the limited time before the Salesforce deadline

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CTMS-41)

**Comment by jwhitlock** [comment]
I think a pre-condition for adding Dependabot is running ``pre-commit`` in CI. This will let us know if a dependency update will break the next developer's commit, so we have a chance to fix it the same time we merge the update.

CI currently runs some linters as a Docker build step, but ``pre-commit`` runs these and a few more. See https://github.com/mozilla-it/ctms-api/issues/66#issuecomment-844525188 for details.

**Comment by leplatrem** [comment]
Done in 1c117e03
