### ISSUE TITLE
Check if `utcnow` is correct for `update_timestamp`

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#180]
The `update_timestamp` schemas use `utcnow`, which has some issues that we discovered in PR #113. We should probably change these to use ``datetime.now(timezone.utc)``.

https://github.com/mozilla-it/ctms-api/blob/bfeac319887cf77a5d05ac44a10853d081753b89/ctms/schemas/email.py#L139-L144

When ``update_contact`` updates the timestamp, it uses ``datetime.now(timezone.utc)``, so this important path is using the right function:

https://github.com/mozilla-it/ctms-api/blob/75e2906c263c599d79d9ea13ac57c5454d07a151/ctms/crud.py#L482-L483

**Comment by bsieber-mozilla** [comment]
References:

https://github.com/mozilla-it/ctms-api/blob/main/ctms/schemas/email.py#L141

https://github.com/mozilla-it/ctms-api/pull/181/commits/0c6c4f19811d1c9739f3eeecf2d866b215cbdb3b

**Comment by bsieber-mozilla** [comment]
I _think_ we can close this, I believe all areas were converted from `utcnow` to the lambda approach
