### ISSUE TITLE
Handle invalid `after` parameter in `/updates`

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#182]
A caller to `/updates` passed `after=null`, which is probably a mistake. This is valid base64, and decodes as `'\x9e\xe9e'`, but does not pass UTF-8 decoding, and raises an exception. This, and other invalid `after` values, should instead return an error with a 4xx status code.

**Comment by bsieber-mozilla** [comment]
a query param with the value of `null` should no longer cause any errors. Although, when a "string" of "null" is seen, a decode will be attempted, and should fail. This failure indicates that the "after" string is likely not a value the compressed in a way the system understands, and is a client err for a misformatted 'after' param.
