### ISSUE TITLE
Potential Optimization for DB Queries, in Background Machinery

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla-it/ctms-api#195]
Just submitting some thoughts after writing the current sync. There could be some potential optimizations, if we see the need. Any other suggestions for optimization are helpful and welcome! 

# Optimize Read
In the query to [read records pending a sync to acoustic](https://github.com/mozilla-it/ctms-api/blob/c394e4cf4c137a663e07edc35b45712547d3480d/ctms/crud.py#L270), there could be multiple rows added to the pending_update, potentially for the same contact. 

At time of sync, say 3 rows were pulled for the same contact id, we'd pull 3 times, and delete 3 times, but it'd likely be redundant. We could "squish" these pending rows, into one record at read, by using the `distinct` ability on the "email_id" column.
 
# Optimize Delete
In the delete query to [remove records that have been successfully synced](https://github.com/mozilla-it/ctms-api/blob/c394e4cf4c137a663e07edc35b45712547d3480d/ctms/crud.py#L316), the current path would only allow for a single row/object to be deleted from the table at a time. 

Upon success, if the optimization is to "squish" rows, then the delete should delete all rows within the table with that email_id, and prior to the sync_time. (Potentially, using a common base query with the read, above.)

# Optimize Retry
In the retry function, we increment the column "retry" for the object/row that is currently up for retry; it's used by the orm as a singular row. An optional path, could be to use the base query and then increment each row (not sure best way to optimize this, taking suggestions!).

_Also, this is probably low priority for the time being._

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CTMS-37)

**Comment by leplatrem** [comment]
background jobs are gone since #896
