### ISSUE TITLE
Add tracing via email string

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#211]
For debugging, I'd like to see the request body for API calls for some users, while omitting them by default. My idea is to look for the string `+trace-me-` in the username portion of the primary email, such as `contact+trace-me-2021@gmail.com`. This allows adding a test email, using [Google's support for creating new email addresses](https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html), in Basket or other systems, and then seeing the details of requests for that contact.

I also considered a tracing header, but that would require client changes, and I'm mostly interested in clients where I don't have control or visibility into their requests. It would be useful when debugging multi-system issues like #184.

Would `+trace-me-` be sufficient opt-in to allow logging of request details?

**Comment by cvalaas** [comment]
I think it's a great idea!
The string needs to be unique enough that real users won't accidentally trigger it, which is what I guess you're asking. It _seems_ like `+trace-me-` would be enough, but I'm not positive.
I'd think for sure adding `+trace-me-mozilla-` would, though that's a mouthful (keyboardful?)

**Comment by jwhitlock** [comment]
Yes, I'm looking for something that won't be accidental, so `+trace-me-mozilla-` is better. I'm not as worried as long as it is below 30 characters or so.

Maybe a random-looking passphrase is better? 1password suggests:
* `+trace-juggle-CAREFUL-`
* `+trace-oath-LETTER-`
* `+trace-thorned-DISORDER-`
* `+trace-gumdrop-PRANK-`
* `+trace-RANCID-swig-`

**Comment by cvalaas** [comment]
I think `+trace-me-mozilla-` is more informative (and easier to remember), but I do love `+trace-gumdrop-PRANK-` and `+trace-RANCID-swig-`

**Comment by jwhitlock** [comment]
Tested when debugging the issue of a Preference Center unsubscribe not setting the opt-out flag
