### ISSUE TITLE
Refactor the logging middleware to use ASGI features

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#217]
Instead of a FastAPI-style middleware, try implementing the logging middleware to use [ASGI](https://asgi.readthedocs.io/en/latest/specs/main.html) features, for better access to the request and response without coordination with the FastAPI endpoints.

The [starlette_exporter middleware](https://github.com/stephenhillier/starlette_exporter/blob/master/starlette_exporter/middleware.py) works at the ASGI level, using the ``http.response.start`` message to get the status, and the ``http.response.body`` message to end the request timer. In a similar way, these messages could be used to:

1) Capture the request details for logging
2) Capture the request body (which may be chunked) for tracing
3) Capture the response status coe
4) Capture the response body, for content length or to determine if the
   email is tracked.

It also may be possible to split the logging and metrics middleware, or make a generic capturing middleware that has logging and metrics as plugins.

Suggested by @bsieber-mozilla on https://github.com/mozilla-it/ctms-api/pull/216#pullrequestreview-659346608

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CTMS-33)

**Comment by grahamalama** [comment]
Since we're going to be using python-dockerflow for logging in #959, we can close this issue
