### ISSUE TITLE
Figure out the process for adding newsletters

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#223]
Previously, Basket held all the metadata for newsletters, available at https://basket.mozilla.org/news/newsletters/. For example, the Salesforce subscription column names were available as the ``vendor_id``.

Currently, there is a list ``MAIN_TABLE_SUBSCR_FLAGS`` in ``ctms/acoustic_service.py``, translating slugs to Acoustic subscription column names:

https://github.com/mozilla-it/ctms-api/blob/230954d2ec44ad0506de0231fdc423ff059485d9/ctms/acoustic_service.py#L95-L98

This means that adding a new newsletter will require CTMS code changes.

We should document the process. We should also consider if we'd rather keep Basket as the source of truth for all newsletter metadata, or split it with CTMS.

A rough draft:

1) Add a new column for the new subscription to Acoustic, default ``0``
2) Update ``ctms/acoustic_service.py`` with the new slug / Acoustic column
3) Update the Basket database for the new slug

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CTMS-31)

**Comment by jwhitlock** [comment]
In a Slack conversation, @pmac suggested re-using the `vendor_id` field in https://basket.mozilla.org/news/newsletters/ as the Acoustic column ID. Instead of using ``MAIN_TABLE_SUBSCR_FLAGS``, ``ctms/acoustic_service.py`` would fetch and parse https://basket.mozilla.org/news/newsletters/ before sending a batch of contacts to Acoustic.

The process to add a new newsletter would then be:

1. Add a new column for the new subscription to Acoustic, default 0
2. Update the basket newsletter database for the new slug and Acoustic ID

**Comment by grahamalama** [comment]
Investigating new methods of adding newsletters separate from the suggestions outlined already in this issue.
