### ISSUE TITLE
ctms-stage: SilverpopResponseException: List with id 1615126 Does Not Exist.

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#232]
In the stage environment, the exception SilverpopResponseException("List with id 1615126 Does Not Exist") is periodically raised.

https://sentry.prod.mozaws.net/share/issue/71d4f02501dd42cab568226d53f430ce/

The calling code is  ``_insert_update_newsletters(table_id=1615126, rows=[])``

https://github.com/mozilla-it/ctms-api/blob/1d2375d3237a35a1e2672d2c112428c01d7b9c72/ctms/acoustic_service.py#L300-L306

This was first seen May 22, and may be related to newsletter updates on May 21.

**Comment by jwhitlock** [comment]
There is not a related issue in `ctms-prod`

**Comment by cvalaas** [comment]
Ah yes, that's because we re-created the newsletter table. I'll get the correct ID shortly

**Comment by cvalaas** [comment]
proper ID is `1639200`

**Comment by jwhitlock** [comment]
Thanks! I'll open a PR against the infrastructure config to update it.

**Comment by jwhitlock** [comment]
Fixed with an update to the environment variable value.
