### ISSUE TITLE
Make GDPR requests easier

### ISSUE THREAD

**Issue by cvalaas** [mozilla-it/ctms-api#240]
For GDPR (et al.) we'll need to provide all the info we have on a given person (email address) and the ability to delete said information.

I imagine there are several ways to accomplish this:
1. Do it all through the CTMS API (explicitly in python?). Probably the Right Way to do this?
2. Do it through CTMS API but using postgres functions
3. Do it directly in the DB using pre-written functions
4. Do it directly in the DB table-by-table

For deletes, make things a bit easier (arguably) by making all the sub-tables ON DELETE CASCADE from `emails`?

I've written basically the same postgres function twice (it'd be easy to combine into one function if desired), once for lookups and once for deletes that can be used expicitly, or as a starting point off which to base other work. The problem with using a postgres function is, of course, that it's somewhat hidden. Anyway, here they are:
```
 CREATE OR REPLACE FUNCTION gdpr_lookup(email_to_find text) RETURNS boolean AS $$
  DECLARE
    email_ids record;
    table_name text;
    --TODO: make these table names an external_table? Like `gdpr_relevant_tables` or something?
    table_names text[] := ARRAY['amo', 'fxa', 'mofo', 'newsletters', 'vpn_waitlist', 'emails'];
    results record;
    result boolean;
  BEGIN
    result := false;
    FOR email_ids IN
      SELECT email_id,'emails' AS lookup_table_name FROM emails WHERE LOWER(primary_email)=LOWER(email_to_find)
      UNION ALL
      SELECT email_id,'fxa' AS lookup_table_name FROM fxa WHERE LOWER(primary_email)=LOWER(email_to_find)
    LOOP
      CONTINUE WHEN email_ids.email_id IS NULL;
      RAISE NOTICE 'Email % (%) found in primary_email field of table %', email_to_find, email_ids.email_id, email_ids.lookup_table_name;
      result := true;
      FOREACH table_name IN ARRAY table_names
      LOOP
        RAISE NOTICE 'Searching % for %', table_name, email_ids.email_id;
        EXECUTE format('SELECT * FROM %I WHERE email_id=$1', table_name)
          INTO results
          USING email_ids.email_id;
        RAISE NOTICE '%', results;
      END LOOP;
    END LOOP;
    RETURN result;
  END;
$$ LANGUAGE plpgsql;
```
and
```
CREATE OR REPLACE FUNCTION gdpr_delete(email_to_find text) RETURNS boolean AS $$
  DECLARE
    email_ids record;
    table_name text;
    --TODO: make these table names an external_table? Like `gdpr_relevant_tables` or something?
    table_names text[] := ARRAY['amo', 'fxa', 'mofo', 'newsletters', 'vpn_waitlist', 'emails'];
    results record;
    result boolean;
  BEGIN
    result := false;
    FOR email_ids IN
      SELECT email_id,'emails' AS lookup_table_name FROM emails WHERE LOWER(primary_email)=LOWER(email_to_find)
      UNION ALL
      SELECT email_id,'fxa' AS lookup_table_name FROM fxa WHERE LOWER(primary_email)=LOWER(email_to_find)
    LOOP
      CONTINUE WHEN email_ids.email_id IS NULL;
      RAISE NOTICE 'Email % (%) found in primary_email field of table %', email_to_find, email_ids.email_id, email_ids.lookup_table_name;
      result := true;
      FOREACH table_name IN ARRAY table_names
      LOOP
        RAISE NOTICE 'Deleting % from %', email_to_find, table_name;
        EXECUTE format('DELETE FROM %I WHERE email_id=$1 RETURNING *', table_name)
          INTO results
          USING email_ids.email_id;
        RAISE NOTICE '%', results;
      END LOOP;
    END LOOP;
    RETURN result;
  END;
$$ LANGUAGE plpgsql;
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CTMS-24)

**Comment by jwhitlock** [comment]
I think ``gdpr_lookup`` is the same as the results of ``GET /ctms?primary_email={email}`` and ``GET /ctms?fxa_primary_email={email}``. What is the advantage of doing it as a direct database query?

We shelved the idea of a delete API like ``DELETE /ctms/{email_id}`` in issue #60. I saw this as a three-phase delete:

* ``DELETE /ctms/{email_id}`` marks a record as deleted, and the data as unavailable in the API
* A deletion action is taken on downstream systems (Acoustic and MoFo systems)
* The soft-deleted CTMS record is actually deleted, using something like ``gdpr_delete`` or an ORM deletion.

**Comment by cvalaas** [comment]
> I think gdpr_lookup is the same as the results of GET /ctms?primary_email={email} and GET /ctms?fxa_primary_email={email}. What is the advantage of doing it as a direct database query?

The only advantage is that it's easier for people who like databases more than web apis, which is probably the set of [me]. (I guess also it's one call vs two). 

The final goal here, I guess, is to make GDPR lookups and deletions as easy/automatable as possible. So probably some yet-to-be-written UI is interacting with CTMS and issuing these GETs and DELETEs. So seems like lookups are handled, now we just need to think about (permanent) deletes. And whether CTMS deletes should trickle downstream to Acoustic/Cinchy, or whether that's a separate job for the aforementioned UI to nuke.
