### ISSUE TITLE
(Collab with MoFo) SFNP dupes - when it is merged into one email record, what is the effect on Cinchy and CTMS?

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-it/ctms-api#248]
During Go-Live we found an issue with email record duplication. See Item #2 in [bug tracking](https://docs.google.com/spreadsheets/d/1GUZ33iHv34ZDAkNRLdDBWM7JTGvG_1gwCNFUey4c1c8/edit#gid=578196499).

SFNP will continue to have dupes, when Stephn merges into one email record, we need to understand what is the ripple effect for both Cinchy and CTMS.

Next step is for team to get together to test it out. (Jackie, Steph, Stephen)

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/CTMS-18)

**Comment by data-sync-user** [comment]
➤ Sarah Chu commented:

Need to understand the path to Cinchy first before we proceed

**Comment by grahamalama** [comment]
Cinchy is no longer used by Mofo, so I'll close this issue
