### ISSUE TITLE
Add a "source"field to CTMS - Update Acoustic

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-it/ctms-api#254]
With SFDC/SFMC, we previously had a "source" field on the contact itself, indicating the source of their very first email subscription. Currently in CTMS, we only track source on a per-newsletter basis. The Foundation needs to know the contact's original source because it tells them how this contact entered the funnel. Potential tasks here include:

* Add a column to the email table in CTMS and update CTMS logic to populate it moving forward
* Back-populate this field in CTMS using historical data from BQ
* Update the API to include this information explicitly 
* Update Cinchy to get this data from CTMS

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/CTMS-12)

**Comment by bsieber-mozilla** [comment]
I believe this Issue and this PR are related: https://github.com/mozilla-it/ctms-api/pull/242

_I'll close the PR shortly, we can reopen if desired._

**Comment by bsieber-mozilla** [comment]
_Was that an automated closure...?_ 
Is this still relevant?
