### ISSUE TITLE
Update CTMS/Acoustic integration to not require a static set of newsletters

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-it/ctms-api#256]
As a MoCo or MoFo marketing professional, I want to be able to self-service my need to create new newsletters, so that I can be responsive to changing business needs without needing support from IT or other engineering resources.

This means being able to set up a new newsletter by making configuration changes to Basket and Acoustic, and without any corresponding code change in CTMS being necessary.

**Acceptance criteria:** the static list of newsletters in our CTMS/Acoustic integration code has been replaced by a mechanism that acquires the newsletters slugs from Basket dynamically.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/CTMS-10)

**Comment by leplatrem** [comment]
This was done, but never closed (see #448 and #456)
