### ISSUE TITLE
Greenhouse set up and integrated with Acoustic for D&I newsletter 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-it/ctms-api#257]
【 highlighted #1d1c1d 】I got a request from Diane Tate and Rashida Houston for a new newsletter. This would be an opt in that job candidates (~1k per day) would see and would need an integration with Greenhouse【 end highlighted 】. 【 highlighted #1d1c1d 】The email stream is intended to help mozilla achieve it's diversity and inclusion goals around hiring.【 end highlighted 】

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/CTMS-9)

**Comment by data-sync-user** [comment]
➤ Sarah Chu commented:

Per Corey: I only know of basket by name.. we do have greenhouse email setup in our spf records and can adjust accordingly if and when the time comes

**Comment by data-sync-user** [comment]
➤ Sarah Chu commented:

Jen H. to reach out to Lauren to see how she can help

**Comment by data-sync-user** [comment]
➤ Sarah Chu commented:

We currently don't have the resource to support this

**Comment by leplatrem** [comment]
Acoustic is gone since #896
