### ISSUE TITLE
Process Payment Methods

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-it/ctms-api#321]
FxA added Stripe "Payment Method" objects to Firestore last week. This broke FxA ingestion until we changed CTMS to ignore unknown object types.
The Payment Methods may contain the data that is currently blank in Acoustic, such as billing country and credit card issuer and last 4 digits. We may want to add a story to the backlog to process Payment Methods.
Products would be very useful as well, but we'll need to encourage the FxA folks to add these to Firestore, since their Redis cache seems good enough for their purposes.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/CTMS-106)

**Comment by data-sync-user** [comment]
➤ Rosanna Fraser commented:

Stephen Hood - adding this story as a placeholder in case you want this fixed. I don’t want to lose sight of it. Please let me know if you want the team to fix this.

**Comment by data-sync-user** [comment]
➤ Rosanna Fraser commented:

Update from standup: Stephen confirmed that this does not need to be fixed before the launch. Will remove from FxA integration release.

**Comment by data-sync-user** [comment]
➤ Stephen Hood commented:

Marketing is now looking for some of this data, particularly billing_country. Trying to work around it for now by querying for country-specific Stripe price_ids and/or using the main contact record’s mailing_country, but this may get elevated soon.

**Comment by data-sync-user** [comment]
➤ Rosanna Fraser commented:

If we do need to fix it, can it be part of the next release that you are planning for Q2?

**Comment by grahamalama** [comment]
Jira issue marked as canceled.
