### ISSUE TITLE
Backfill current subscription state of existing contacts in CTMS and Acoustic

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-it/ctms-api#331]
As a product manager, I want all existing contacts in both CTMS and Acoustic to have an accurate subscription state upon launch of this project, both so that our data set reflects reality and so that Marketing can potentially reach out to existing subscribers.

Acceptance criteria:

* Production data in CTMS and Acoustic have been bulk-updated so that every contact has subscription status that reflects what is found in Stripe.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/CTMS-80)

**Comment by data-sync-user** [comment]
➤ Rosanna Fraser commented:

Not required to do the first use case

**Comment by data-sync-user** [comment]
➤ Rosanna Fraser commented:

This no longer fits in our scope for FxA Integration Q4 project.

**Comment by data-sync-user** [comment]
➤ Stephen Hood commented:

Just learned that FxA backfilled all US and CA Stripe subscription data back on 1/21/22. This was accomplished by importing it from BQ into FxA (the Data team has its own direct integration Stripe, to support product dashboards). I am now working with FxA to get a backfill of all non-US/CA data into their backlog.

**Comment by bsieber-mozilla** [comment]
https://docs.google.com/document/d/19LsShP37g1FUkqEMCfStXDWDPQokRtOv3d8SdrQU4lo/edit#heading=h.abwrfe735a9t

**Comment by bsieber-mozilla** [comment]
I believe we can close this issue now, given the efforts from earlier to backfill/align the contacts.

_Please feel free to reopen if there is more to this issue._
