### ISSUE TITLE
Cleanup orphaned / outdated Stripe objects

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#346]
The CTMS database will accumulate orphaned and outdated Stripe objects. These could be periodically cleaned up:

* Subscriptions and Invoices for deleted Customers
* Invoices and Invoice Line Items older than the current Invoice

This could be a script that is launched by a daily cron task.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CTMS-120)

**Comment by grahamalama** [comment]
Closing this for now since it hasn't popped up recently as an issue. We can reopen this if warrants further investigation.
