### ISSUE TITLE
Codeowners: SysEng, a new github team, or something else?

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla-it/ctms-api#366]
SysEng was originally suggested in this closed PR: https://github.com/mozilla-it/ctms-api/pull/356 
However, a new github team dedicated to ctms could be the right approach (https://github.com/mozilla-it/ctms-api/pull/356#issuecomment-1027194469).

What are your thoughts?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CTMS-128)

**Comment by jwhitlock** [comment]
During initial development, I found it disruptive to have reviewers who never reviewed a PR. I think a focused team based on people that will review the PRs is a good solution.
