### ISSUE TITLE
Replace list of of usernames in `.github/CODEOWNERS` with group

### ISSUE THREAD

**Issue by grahamalama** [mozilla-it/ctms-api#399]
So we don't have to make PRs for every team change in the future, we can set up a group in the org to designate as a codeowner. Then we can manage additions / removals through Github.

**Comment by grahamalama** [comment]
@bkochendorfer I think you'd be the one to create the group? Then I can make a PR to change the CODEOWNERS file

**Comment by grahamalama** [comment]
Update: @bsieber-mozilla created [@mozilla/ctms-reviewers ](https://github.com/orgs/mozilla/teams/ctms-reviewers/members) and opened #407 . I think all we need to do is grant the proper permissions for that group to this repo, and we'll be g2g

**Comment by bsieber-mozilla** [comment]
Unfortunately cant use cross-org groups; we'll need a group in moz-it--and y'all added into moz-it

**Comment by bsieber-mozilla** [comment]
Ok, this has been done! New group: @mozilla-it/ctms-reviewers
