### ISSUE TITLE
Make sure all "weird" data is regression tested

### ISSUE THREAD

**Issue by imbstack** [mozilla-it/ctms-api#42]
Basically the contents of the notes column of https://docs.google.com/spreadsheets/d/1_cFct8EAUxiow_zgS8fwQPUyw2yHx0TQfpXVCABKS5Q/edit#gid=0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CTMS-52)

**Comment by jwhitlock** [comment]
Is this issue still relevant?

**Comment by bsieber-mozilla** [comment]
I think we can close this

**Comment by grahamalama** [comment]
Closing this based on @jwhitlock and @bsieber-mozilla's latest comments
