### ISSUE TITLE
Migrate from AWS to SaaS-based Sentry?

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla-it/ctms-api#446]

**Comment by bkochendorfer** [comment]
I do see a CTMS project in the SaaS Sentry.

**Comment by bsieber-mozilla** [comment]
I see these in the SaaS sentry; 
https://sentry.io/organizations/mozilla/issues/?project=6415391
https://sentry.io/organizations/mozilla/issues/?project=6415853

but the aws one seems to be having much more activity:
https://sentry.prod.mozaws.net/operations/ctms-prod/
https://sentry.prod.mozaws.net/operations/ctms-stage/

**Comment by bsieber-mozilla** [comment]
Thanks @bkochendorfer ! We're now on the SaaS version!

A followup request is found here in the [slack thread](https://mozilla.slack.com/archives/C023R6MCY4V/p1668548268066919?thread_ts=1668532779.249109&cid=C023R6MCY4V).

I think an additional environment variable SENTRY_ENVIRONMENT (values: stage/prod) will enable that request. But perhaps this should be an alternate issue.
