### ISSUE TITLE
Document inventory of workflows

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla-it/ctms-api#455]
eg.

* A user signs up on a newsletter
* A user signs up for a waitlist in a certain country
* A user subscribes to Mozilla VPN
* MoFo collects mofo_relvant contacts in bulk to update their data fabric (cinchy) based on time intervals…? Why? What are they using the data for? Which data are they looking at?

**Comment by bsieber-mozilla** [comment]
_@leplatrem originally made this but I have converted this to an issue and assigned it to myself_

**Comment by bsieber-mozilla** [comment]
Relevant material:

- https://mozilla-hub.atlassian.net/browse/CTMS-139
- https://docs.google.com/document/d/1eOGptNiItomdavzbvnB10mYzQi2RUQYxD8L9mJD3Hvk/edit# 
    - Nov 17

**Comment by bsieber-mozilla** [comment]
Had an initial meeting with Andra and Alex from MoFo, with Bindya from MoCo: https://docs.google.com/document/d/1i0MTtiBFbiL9AJcBothlnvcOTklTE61Jb4xIFXERc3E/edit

**Comment by bsieber-mozilla** [comment]
Hoping to go into a deeper tech discussion with Dan from MoFo

**Comment by bsieber-mozilla** [comment]
https://docs.google.com/document/d/1_5NxJBKszFmw5YwleWeXd4B6_aoligj1pNvJpsX4nZQ/edit

**Comment by bsieber-mozilla** [comment]
<p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" id="docs-internal-guid-a0346cba-7fff-59f0-73fd-342cb72cea7a"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Process List :&nbsp;</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The table below contains a list of processes&nbsp; identified as processes that utilize CTMS&rsquo;s capabilities to support them.</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Process name | Team
-- | --
Email Campaign Management Hygiene List | MOFO
Newsletter Co-ordination | MOFO
Create and Use FireFox Account | MOCO FXA
Create and Cancel a subscription | MOCO FXA
Donation Process | MOFO
Information Retrieval | MOCO
Delete request | MOCO
Unsubscribe request | MOCO

</div>

**Comment by bsieber-mozilla** [comment]
Where/How do we want to view this documentation?

**Comment by leplatrem** [comment]
> Where/How do we want to view this documentation?

Just to be safe, since this repo is public, we could start on Google Docs.

Related #560

**Comment by bsieber-mozilla** [comment]
Shortcut for document added to Syseng>CTMS -- Google Drive. 

https://docs.google.com/document/d/1MiHhkO29h_TZbwdkNRGYNUQmWAEYI9rAXFWzbkw5LD4/edit#heading=h.aon7aoyan8l5
