### ISSUE TITLE
Use of SENTRY_ENVIRONMENT to designate different envs (instead of different projects)

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla-it/ctms-api#458]
Thanks @bkochendorfer ! We're now on the SaaS version!

A followup request is found here in the [slack thread](https://mozilla.slack.com/archives/C023R6MCY4V/p1668548268066919?thread_ts=1668532779.249109&cid=C023R6MCY4V).

I think an additional environment variable [SENTRY_ENVIRONMENT](https://docs.sentry.io/platforms/python/configuration/options/#environment) (values: stage/prod) will enable that request. But perhaps this should be an alternate issue.

_Originally posted by @bsieber-mozilla in https://github.com/mozilla-it/ctms-api/issues/446#issuecomment-1315907303_

**Comment by bkochendorfer** [comment]
No problem, this is deployed to stage and prod. I see the environments as requested above in the one project.

**Comment by bsieber-mozilla** [comment]
Thanks @bkochendorfer! I see stage/prod (as well as production) environments in the ctms-api project space.
