### ISSUE TITLE
Establish DORA metrics

### ISSUE THREAD

**Issue by grahamalama** [mozilla-it/ctms-api#478]
We should make a dashboard that highlights the 4 DORA metrics:

- [ ] Deployment Frequency: Refers to the frequency of successful software releases to production.
- [ ] Lead Time for Changes: Captures the time between a code change commit and its deployable state.
- [ ] Mean Time to Recovery: Measures the time between an interruption due to deployment or system failure and full recovery.
- [ ] Change Failure Rate: Indicates how often a team’s changes or hotfixes lead to failures after the code has been deployed.

**Comment by grahamalama** [comment]
`Deployment frequency` and `Lead Time for Changes` seem relatively easy to measure. Less sure about `Mean Time to Recovery` or `Change Failure Rate`.

**Comment by bsieber-mozilla** [comment]
Sentry might be useful for the `Change Failure Rate`--I believe there's a way we can segment by release

**Comment by grahamalama** [comment]
Nice, thanks @bsieber-mozilla.

I created https://mozilla-hub.atlassian.net/browse/SVCSE-938 which will hopefully allow us to pull Sentry data into Grafana.
