### ISSUE TITLE
Rethink Push/Pull Subscription

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla-it/ctms-api#485]
- [ ] Investigate Payload Size
- [ ] How much information do we use?
- [ ] Stripe API Key?
- [ ] Can we increase the performance of DB Queries (batching, loop-updates, ...)

**Comment by grahamalama** [comment]
#445 seemed to address the problem that caused us to create this issue. Closing this for now, but we continuing to think about how Acoustic gets access to Stripe data. This might mean removing this subscription entirely.
