### ISSUE TITLE
Background pod responsible for clearing Acoustic backlog crashes often

### ISSUE THREAD

**Issue by grahamalama** [mozilla-it/ctms-api#496]
The Kubernetes pod that runs our Acoustic Sync background job (`ctms-background-xxxxx`) crashes very often. 

![image](https://user-images.githubusercontent.com/20747904/209167869-6eb03785-8c9c-482b-9990-45458cfb7b90.png)

We do have the Acoustic Sync job configured to sync a batch of contacts and then sleep for a certain period of time. But the pod should not crash and restart this often.

**Comment by ahoneiser** [comment]
After some research with @izo3, thinks look like the Deployments `livenessProbe` is facing a race condition that's causing the container to be re-spawned a lot. We've updated the `livenessProbe.timeoutSeconds` to a larger value than before and immediately got restarts dropping to 0.

**Comment by ahoneiser** [comment]
#497 should help with troubleshooting :slightly_smiling_face:
