### ISSUE TITLE
improve DSARS/GDPR deletion request handling

### ISSUE THREAD

**Issue by ahoneiser** [mozilla-it/ctms-api#529]
# tracking issue for DSARS/GDPR deletion requests

DSARS/GDPR deletion requests are currently handled in a primarily manual process, a couple of the tasks could be automated to reduce maintenance of resources as well as to reduce SRE time. Ideas to improve the process:

* add an API endpoint to CTMS to make the workflow easier to handle
* add a script / k8s cronjob to do the actual deletion from within the application pods

**Comment by mostlygeek** [comment]
Also this doc: https://docs.google.com/document/d/1ngAV3bxuy3ruxgLQyFYKtfqTKMU7Gx3UXbghA118a_Y/edit#heading=h.6mvcyhh9vp7u

**Comment by mostlygeek** [comment]
DSARS/GDPR has been something we would like to see more automated everywhere.  Not just CTMS.  Besides the reducing of manual effort it'll also allow us to be more consistent and thorough.

**Comment by leplatrem** [comment]
Related #240
