### ISSUE TITLE
CTMS code comparison over Time-Ranges:

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla-it/ctms-api#531]
----
Compare main to...
- 1 day ago: https://github.com/mozilla-it/ctms-api/compare/main%40{1.day.ago}...main
- 2 weeks ago: https://github.com/mozilla-it/ctms-api/compare/main%40%7B2.weeks.ago%7D...main
- 1 month ago: https://github.com/mozilla-it/ctms-api/compare/main%40%7B1.month.ago%7D...main
- 6 months ago: https://github.com/mozilla-it/ctms-api/compare/main%40%7B6.months.ago%7D...main
- 1 year ago: https://github.com/mozilla-it/ctms-api/compare/main%40%7B1.year.ago%7D...main

###### provided for reference of progress/work/code over time

----

**Comment by bsieber-mozilla** [comment]
@mostlygeek this might not be the highest fidelity--however this might provide a minor view of work involved in the project over different time ranges: to understand the "jobs-done" over a time--which could help shed some light on the ["investment" component.](https://mozilla.slack.com/archives/C022K8JD8QY/p1675195614225209?thread_ts=1675191331.845879&cid=C022K8JD8QY). 

_However, there are quite a few `dependabot` commits in there to evade._

**Comment by mostlygeek** [comment]
Thanks, but this isn't really what I'm looking for.

**Comment by bsieber-mozilla** [comment]
You're welcome, I know this wasn't the full request or even pertaining to it--it's adjacent; I thought it could be helpful to have these queries "bookmarked". 

_Closing this issue_

**Comment by mostlygeek** [comment]
That's a perspective I didn't consider last night.  

Thinking about it a bit more, being able to answer both of these questions quickly would be beneficial: 

- how much did we invest into this project? - captured by our OKRs and Off OKR sheet
- where did we invest that?  - this issue partly answers that
