### ISSUE TITLE
Add POST /ctms to create a contact

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#54]
Add a ``POST /ctms`` endpoint that will create a contact. The body is JSON that includes the contact data.

- [x] The elements ``email.primary_email`` and ``email.basket_token`` are required, and an error (TBD) is returned if omitted.
- [x] If there are existing contacts with the same values for ``email.primary_email`` and ``email.basket_token``, an error (TBD) is returned.
- [x] The element ``email.email_id`` is optional. If omitted, a new UUID is generated. If provided, and an existing contact has the same ``email_id``, an error (TBD) is returned.
- [x] Other items are optional, and can be omitted or sent with default values
- [x] If a group (like ``amo``) is sent with the default values, it is treated as if it was omitted (i.e., no related ``amo`` row is created) 
- [x] The return is a redirect to the newly created contact, ``/ctms/{email_id}``
- [ ] `basket_token` is not required

Tracked as Jira:OSS-305

**Comment by jwhitlock** [comment]
I'm wrong about ``basket_token`` being required. Cinchy / Mozilla Foundation may create records without a basket token.

@imbstack do you want to add this to the list for this issue, or track with a new one?

**Comment by imbstack** [comment]
Added here! I'll get it in the PR I'm trying to make today
