### ISSUE TITLE
Add PUT /ctms/{email_id} to insert or update a contact

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#55]
Add a ``PUT /ctms/{email_id}`` endpoint that will insert or update a contact. The body is JSON that includes the contact data.

* The element ``email.primary_email`` ~~and ``email.basket_token``~~ is required, and an error (TBD) is returned if omitted. The ``email_id`` in the URL is a third ID.
  * If ``email.email_id`` is included in the data, it must match ``email_id`` in the URL, or an error (TBD) is returned
  * If an existing contact matches the ~~three~~ two IDs, it is considered an update.
  * If no existing contact matches any of the ~~three~~ two IDs, it is considered an insert. 
  * If an existing contact matches some but not all of the IDs, a ``409 Conflict`` error is returned.
* Other items are optional
* If the action is an insert:
  * If a group (like ``amo``) is sent with the default values, it is treated as if it was omitted (i.e., no related ``amo`` row is created)
  * The return is a ~~``201 Created``, and the body is the new contact JSON~~ ``303 See Other`` to ``/ctms/{email_id}`` (see #303)
* If the action is an update:
  * ~~If an item is omitted, the existing value for that item is unchanged~~ - Moved to ``PATCH``, #128 
  * If an item is included, the existing value is updated
  * If a group (like ``amo``) is sent with all default values, any existing row is deleted
  * ~~To delete a group, send TBD (``None``? ``{}``? ``{"delete": true}``?)~~ - Moved to ``PATCH``, #128 
  * The return is a ~~``200 OK``, and the body is the updated contact JSON~~ ``303 See Other`` to ``/ctms/{email_id}`` (see #303)

Tracked as part of Jira:OSS-305

**Comment by jwhitlock** [comment]
There are a few To Be Determined (TBD) placeholders, here's some proposals, saving the hardest for last:

### The elements ``email.primary_email``, ``email.basket_token`` are required, and an error (TBD) is returned if omitted.

I think this is a ``400 Bad Request``, but from the POST we get a ``422 Unprocessable Entity`` for free with pydantic, with this body:

```
{
  "detail": [
    {
      "loc": [
        "body",
        "email",
        "primary_email"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    },
    {
      "loc": [
        "body",
        "email",
        "basket_token"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    },
    {
      "loc": [
        "body",
        "email",
        "email_id"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    }
  ]
}
```

### If email.email_id is included in the data, it must match email_id in the URL, or an error (TBD) is returned

I want to remove the "if" and say you have to include ``email.email_id``, which is how I expect clients to implement upserts. However, the server-side logic is similar, that the URL and the body need to match. My preferences are:

* If we can convert the check to a Pydantic check, then return a ``422 Unprocessable Entity``. This is ideal because Pydantic can do a UUID-to-UUID compare and ignore details of formatting (upper vs lower, human-friendly dashes, etc.)
* If it is too tricky to use Pydantic, due to the optional requirement or lack of time, a ``400 Bad Request`` with a body ``{"detail": "Email ID in URL does not match email.email_id in body"}`` (and doesn't repeat the values) would be fine. 

## To delete a group, send TBD (None? {}? {"delete": true}?)
The requirement to deleting data from a group was taken from basket, where deleting an account (such as an addons.mozilla.org account) deletes the related data. There was some discussion on issue #54 about how to delete a group on update. This issue proposed two ways:

* Send default values, delete the row. This should be possible, but requires 1) CTMS can compare the submitted data to the default values correctly, and 2) the client knows what the default values are. It seems awkward, and maybe not worth the effort.
* Send a special value, to be determined (TBD) . This seems like a direct and clear way for the client to communicate this.

Building on @cvalaas's proposal, I think this will work:

```json
{
  "amo": {
    "_DELETE": true
  },
  "email": {
    "(other)": "(content...)"
  }
}
```

The leading underscore and the shouting in `_DELETE` implies it is not a normal value, and it is fairly clear what action is intended.

**Comment by cvalaas** [comment]
I don't think basket_token should be required. Requests initiated from SFNP (coming through Cinchy) will not have such a token.

**Comment by cvalaas** [comment]
Yeah, I guess it should be NULLable. My mistake.
Since Cinchy will be doing upserts, I don't think it can be required either way...

**Comment by jwhitlock** [comment]
I'm also mistaken, ``basket_token`` is already optional. It can be ``null`` in the database, but if set, still needs to be unique. Some parts of the API already mark it as optional, it needs to be optional here (I've marked out that section) and at ``POST``.

**Comment by jwhitlock** [comment]
I've marked up the issue to reflect what was implemented. Some of the design items were moved to other bugs:

* Issue #128 - Implement partial updates and special commands on ``PATCH /ctms/{email_id}``
* Issue #105 - Returns that are more compatible with the Swagger UI
