### ISSUE TITLE
Follow up of #562: Migrate Acoustic newsletter workflow off main table to relational table

### ISSUE THREAD

**Issue by grahamalama** [mozilla-it/ctms-api#563]
Related: #562 
- [x] migrate `sub_<newsletter>` data to relational table
- [ ] convert existing Acoustic queries to use newsletter relational table
- [ ] delete old `sub_<newsletter>` columns

**Comment by leplatrem** [comment]
Add `create_date` to the list? 
https://github.com/mozilla-it/ctms-api/issues/812
