### ISSUE TITLE
CTMS-146: Add a command to detect or fix diffs between CTMS and Acoustic

### ISSUE THREAD

**Issue by leplatrem** [mozilla-it/ctms-api#565]
https://mozilla-hub.atlassian.net/browse/CTMS-146

If a user unsubscribes from a newsletter but for any reason the Acoustic data is not in sync, they will continue to receive emails.

We need a consistency-check command, that should report and ideally fix the diffs between CTMS and Acoustic

**Comment by grahamalama** [comment]
Maybe something for another issue, but perhaps we could also leverage [Acoustic Webhooks](https://help.goacoustic.com/hc/en-us/articles/360039881833-Create-custom-workflows-with-webhooks) here to keep things in sync? So that if a change is made on the Acoustic side, it's propagated to CTMS.

**Comment by bsieber-mozilla** [comment]
There is some ongoing effort in acoustic to clean up the system with a contractor--they had a single session last week. The documents in this drive show some of the current effort: https://docs.google.com/spreadsheets/d/1rWMlkvLlbZhDXX4ZYvj4QJ7j0k1JYlXR/edit?usp=share_link&ouid=118205549745087972930&rtpof=true&sd=true

**Comment by leplatrem** [comment]
This command is very likely to never exist. The dataset is too big in front of the limited features of the Acoustic API. 

We've decided to change the strategy:
- fail loudly on synchronization errors
- use `acoustic resync` (#588) 
- or use `acoustic.py dump` (#686) to dump big parts of the database and re-upload to Acoustic FTP

Let's mark this as closed. Feel free to re-open if good reasons to do so
