### ISSUE TITLE
How to deal with unresolved "Pending" Contacts

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla-it/ctms-api#575]
Another part of this resync; how does this relate to contact's that are stuck in a pending_state with more than the allotted retries? (Or should that be handled elsewhere?)

https://earthangel-b40313e5.influxcloud.net/d/7FxRQoNVz/ctms-prod-dashboard?orgId=1&viewPanel=30&from=1677790733274&to=1678136333274

_Originally posted by @bsieber-mozilla in https://github.com/mozilla-it/ctms-api/issues/569#issuecomment-1456989067_

**Comment by bsieber-mozilla** [comment]
@leplatrem https://github.com/mozilla-it/ctms-api/pull/569#issuecomment-1458031838

**Comment by leplatrem** [comment]
From what I can see in Papertrail, we have lots of errors about invalid emails.

**Comment by leplatrem** [comment]
This was handled already.

We now have:
- `acoustic.py resync`
- Sentry on Acoustic sync errors
