### ISSUE TITLE
Investigate `sub_firefox_news` Basket slug mapping

### ISSUE THREAD

**Issue by grahamalama** [mozilla-it/ctms-api#598]
Right now https://github.com/mozilla-it/ctms-api/blob/99f3dbdae8c718e1360aec116ce0d1fa3a0fc833/migrations/versions/20221115_f8b8f6aa0e96_add_acoustic_newsletter_mapping.py#L36 
two Basket slugs are mapped to the same Acoustic column:
```
firefox-news -> sub_firefox_news
mozilla-and-you -> sub_firefox_news
```
Questions to answer:
- The `firefox-news` slug is [not present](https://basket.mozilla.org/news/) in Basket. Should we should delete this mapping?

- Are there people subscribed to the `firefox-news` newsletter in CTMS? Can they be migrated to `mozilla-and-you` or deleted?

- Should we limit things in the database so that only one basket slug may be mapped to one Acoustic column?

**Comment by leplatrem** [comment]
Mappings are gone since #896
