### ISSUE TITLE
Add DELETE /ctms/{email_id} and soft deletion

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#60]
Add a ``DELETE /ctms/{email_id}`` method to soft-delete a contact:

* Add a database field to ``email`` representing a soft-delete, or a soft-delete table
* When called, soft-delete the record, return ``410 Gone``
* ``GET /ctms/{email_id}`` returns a ``404 Not Found`` or ``410 Gone``
* ``POST /ctms`` or ``PUT /ctms/{email_id}`` is allowed without violating uniqueness or ID collisions

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CTMS-51)

**Comment by jwhitlock** [comment]
Moving to Post-Salesforce milestone, since we're not planning to add a deletion process to the API before launch.

**Comment by grahamalama** [comment]
Closing this since https://github.com/mozilla-it/ctms-api/pull/548 added a delete endpoint, however:
- It's a "hard delete" endpoint, not soft
- it's `DELETE /ctms/{primary_email}`, not `DELETE /ctms/{email_id}`
