### ISSUE TITLE
Hygiene List Automation -- Removing Manual Touches and Security Risks with User Data

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla-it/ctms-api#604]
- [ ] Implement one improvement to the system
    - [ ] https://docs.google.com/document/d/1CHE3o7ZHprNBaN-2RvgApbI_8kpanJGdQ-ALZZZSRtE/edit#heading=h.es6mox566qh8
    - [ ] Everest API https://developer.everest.validity.com/#1f95fcfb-c4c2-4a8c-9391-b18dc757979b
        - [ ] List Validation APIs: `Create List` and `List by ID`
        - [ ] The process for Everest is: submit job (create list), poll job for completion (list by id), export job results (`endpoint`s from results)

_Originally posted by @bsieber-mozilla in https://github.com/mozilla-it/ctms-api/issues/595#issuecomment-1467209526_

**Comment by bsieber-mozilla** [comment]
- [ ] Acoustic Product Consultant Planning / Data 1.3 Review
    - When: Wednesday, April 12⋅1:00 – 2:00pm
    - Who: Bryan // William

**Comment by bsieber-mozilla** [comment]
https://docs.google.com/document/d/1w4-uP_YVhK36T-mC8n31tPhcqNZImZ-f/edit

**Comment by bsieber-mozilla** [comment]
https://docs.google.com/document/d/1CHE3o7ZHprNBaN-2RvgApbI_8kpanJGdQ-ALZZZSRtE/edit#heading=h.es6mox566qh8

**Comment by grahamalama** [comment]
I think the processes described by some of the docs included in this issue are obsolete to the point that we can safely close this issue.
