### ISSUE TITLE
Retry all PendingAcoustic Records

### ISSUE THREAD

**Issue by grahamalama** [mozilla-it/ctms-api#620]
Requirement: 
- CTMS v2 deployed
    - Introduces logs that are essential for determining why records are not properly being synchronized.

Tasks:

- [x] Coordinate with SRE (Andre) to set the value of the "retry" column in the `pending_acoustic` table to 0
    - [x] https://mozilla-hub.atlassian.net/browse/SE-3498
- [x] Follow along with logs; catalog, create issues, and link sentry alerts to the gh issues

**Comment by bsieber-mozilla** [comment]
_No longer blocked due to successful release of v2_

**Comment by bsieber-mozilla** [comment]
Related: https://mozilla-hub.atlassian.net/browse/SE-3497

**Comment by bsieber-mozilla** [comment]
We wait until the above card can be processed--then...

After the columns are reset--this should enable us to see logs and resolve errors that might pop up in sentry.

**Comment by bsieber-mozilla** [comment]
https://mozilla-hub.atlassian.net/browse/SE-3498

**Comment by leplatrem** [comment]
https://mozilla-hub.atlassian.net/browse/SE-3501

**Comment by leplatrem** [comment]
We obtained 4K+ sentry events https://mozilla.sentry.io/issues/4115635634/?environment=prod-gcp&project=6415391&query=is%3Aunresolved&statsPeriod=14d&stream_index=3

and now have 450 contacts rejected (cf Grafana)

If those ~450 contacts had bad emails (that would never sync) and [we retried them 10 times](
https://github.com/mozilla-it/ctms-infra/blob/9fb682815bed5b2a365f4e4c4d0abe84b4eefa78/terraform/secret.tf#L46
 ), thats ~4500 errors


We can now decide what to do with those contacts, but this issue can now be closed
