### ISSUE TITLE
Disconnect CTMS <--> Cinchy Services (Decommissioned Client Cleanup)

### ISSUE THREAD

**Issue by grahamalama** [mozilla-it/ctms-api#626]
Since Mofo's SNFP migration will decommission Cinchy, we should remove any code or documentation that refers to it.

----

- [x] Remove Cinchy API Key from CTMS DB: https://mozilla-hub.atlassian.net/browse/SE-3495
- [x] Adjust System's Diagrams and remove Cinchy/CTMS relationship
- [x] Update documentation where there are mentions of Cinchy (SFNP, using Apex, is the new integration path with our MoFo partners)

**Comment by bsieber-mozilla** [comment]
![Image](https://user-images.githubusercontent.com/53873986/232928278-0ca0bec9-414a-42fa-a9a4-a3d4c23b7aea.png)

**Comment by bsieber-mozilla** [comment]
#643 should resolve the remaining tasks in this card
