### ISSUE TITLE
Add "make lint"

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-it/ctms-api#66]
Add a `make lint` command that runs the linter inside the Docker container. 

Currently, ``script/lint.sh`` can only run inside a ``poetry shell`` on the development system, because ``detect-secrets-hook`` requires ``git``, which is not in the Docker container, after PR #12. I don't think we should add ``git`` to the container, since I don't think we should commit inside of the container either. Some options are to skip checking secrets when ``git`` is not available, or generate the file list without ``git``.

**Comment by bsieber-mozilla** [comment]
A potential solution could be this...https://github.com/mozilla-it/ctms-api/issues/66

`make lint` should do the lint checking through docker

**Comment by jwhitlock** [comment]
As of the recent changes, we have these linters:

* [bandit](https://github.com/PyCQA/bandit) - Security analysis of Python code
* [black](https://black.readthedocs.io/en/stable/) - Formats Python code
* [detect-secrets](https://github.com/Yelp/detect-secrets) - Look for secrets in code an docs
* [isort](https://github.com/PyCQA/isort) - Sorts Python imports
* [seed-isort-config](https://github.com/asottile-archive/seed-isort-config) - Statically populate the ``known_third_party`` ``isort`` setting. (deprecated with `isort` 5)
* [mypy](https://mypy.readthedocs.io/en/stable/) -Static type checker for Python
* [pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks) - A collection of hooks for [pre-commit](https://github.com/pre-commit/pre-commit), including:
  - [check-added-large-files](https://github.com/pre-commit/pre-commit-hooks#check-added-large-files) - Prevent committing giant files
  - [check-json](https://github.com/pre-commit/pre-commit-hooks#check-json) - Attempts to load all json files to verify syntax.
  - [detect-private-key-file](https://github.com/pre-commit/pre-commit-hooks#detect-private-key)
  - [end-of-file-fixer](https://github.com/pre-commit/pre-commit-hooks#end-of-file-fixer) - Makes sure files end in a newline and only a newline
  - [pretty-format-json](https://github.com/pre-commit/pre-commit-hooks#pretty-format-json) - Checks that all your JSON files are pretty
  - [trailing-whitespace](https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace) - Trims trailing whitespace. 
* [pylint](http://pylint.pycqa.org/en/latest/) - Enforces Python coding standards

We have three ways to run linting:

* ``scripts/lint.sh`` is run manually, and runs against all the files in the project.
* ``pre-commit`` is run before commits if [installed by the committer](https://github.com/mozilla-it/ctms-api/blob/main/guides/developer_setup.md#pre-commit). By default, it uses ``.git`` to only run on the files to be committed.
* ``make lint`` explicitly builds the [lint step](https://github.com/mozilla-it/ctms-api/blob/2f8844479ee170a435f3c4ff572fb53756237980/docker/Dockerfile#L81-L89) of the Dockerfile. It runs against files in the docker image

Some run in check mode, failing if a problem is found. Others can fix problems, although they sometimes exit with an errorcode if changes were made. Here's the matrix:

|Test|``scripts/lint.sh``|``pre-commit``|``make lint``|
|-:|:-:|:-:|:-:|
|``bandit``|check|check|check|
|``black``|fix|fix|check|
|``detect-secrets``|check (1) |check| |
|``isort``|fix|fix|check|
|``seed-isort-config``| |fix| |
|``mypy``|check|check|check|
|``pre-commit-hooks``| |fix| |
|``pylint``|check|check|check|

Notes:
1.  ``scripts/lint.sh`` runs ``detect-secrets`` from the "host", when ``git`` is available, not inside the docker image

``pre-commit run --all`` does what ``scripts/lint.sh`` does and more, but requires ``git`` and can't be run inside the container. Running inside the container is not a requirement, but it does keep the host system cleaner for new CTMS developers.

I'm not sure how much further we can go to unify the linters. One possibility is to run ``pre-commit run --all`` as a build step in CircleCI, in case the submitter (such as Dependabot, issue #172) didn't run ``pre-commit``.  Then, the docker build step would be the redundant linter.

I'm inclined to close this issue (since I've mostly fulfilled the original issue), and revisit after some further thought or as part of #172.

**Comment by jwhitlock** [comment]
I'm going to bundle running ``pre-commit run --all`` in CI with turning on Dependabot.
