### ISSUE TITLE
Unexpected behavior when `PUT`ing a contact with legacy waitlists

### ISSUE THREAD

**Issue by grahamalama** [mozilla-it/ctms-api#734]
1. POST contact with a legacy waitlist field (VPN):
```
...
 'relay_waitlist': None,
 'vpn_waitlist': {'geo': 'us', 'platform': None},
 'waitlists': []
}
```
success ✅ 

2. GET that object back, looks like this:
```
 'relay_waitlist': {'geo': None},
...
 'vpn_waitlist': {'geo': 'us', 'platform': None},
 'waitlists': [{'fields': {'geo': 'us', 'platform': None},
                'name': 'vpn',
                'source': None}]
}
```
3. PUT the contact, signing up for another waitlist through a legacy field (Relay):
```
 'relay_waitlist': {'geo': 'us'},
 'vpn_waitlist': {'geo': 'us', 'platform': None},
 'waitlists': [{'fields': {'geo': 'us', 'platform': None},
                'name': 'vpn',
                'source': None,
                'subscribed': True}]
}
```

Expected: User is signed up for the relay and vpn waitlists
Actual: User is only signed up for the VPN waitlist

I'm pretty sure that's because of [this](https://github.com/mozilla-it/ctms-api/blob/82d2f70c9905d0797135b60355a2929c4a4d928b/ctms/backport_legacy_waitlists.py#L23-L25).

**Comment by leplatrem** [comment]
Since Basket [does not set those fields anymore](https://github.com/mozmeao/basket/pull/962/files#diff-d6aadfae5982cb77055ddff406cd982f1dce929c139d9dd562ca488f0b9ad568L86), this is less urgent than #733
