### ISSUE TITLE
`acoustic.py resync` should set `retries` column to `0`

### ISSUE THREAD

**Issue by leplatrem** [mozilla-it/ctms-api#806]
If a contact has `retries=5`, it won't be synchronized.

If this contact is among the specified list for `acoustic.py resync` then it won't be resynced.

https://github.com/mozilla-it/ctms-api/blob/bd8b23d99efb6e4bb0523a66e7efd415236e2b44/ctms/crud.py#L334

We should upsert the `PendingAcousticRecord` with `retries=0`

**Comment by grahamalama** [comment]
Possibly related, but I just noticed that we don't have a unique index for `email_id` on the `"pending_acoustic"` table.

So not only does `bulk_schedule_acoustic_records` not reset the retry column, but it adds a new record:

```python
email = Email(...)
pending_record = PendingAcousticRecord(email_id=email.email_id, retry=5)
dbsession.add(email)
dbsession.add(pending_record)
dbsession.commit()

bulk_schedule_acoustic_records(dbsession, [email.primary_email])
dbsession.commit()

print(len(dbsession.query(PendingAcousticRecord).all()))

2
```
