### ISSUE TITLE
Sync a contact's `create_timestamp` to Acoustic as an Acoustic date

### ISSUE THREAD

**Issue by grahamalama** [mozilla-it/ctms-api#812]
https://help.goacoustic.com/hc/en-us/articles/360043349433-Work-with-database-fields

We currently sync a contact's `create_timestamp` to Acoustic in a format that is incompatible with Acoustic's `Date` type. As @leplatrem discovered:

currently on `main`
```
poetry run ctms/bin/acoustic.py dump --query="SELECT email_id FROM emails LIMIT 1;"

Dump CSV for 1 contacts [y/N]? y
...
...05/21/2021 16:39:02,...
```

from `v2.1.0`
```
poetry run ctms/bin/acoustic.py dump --query="SELECT email_id FROM emails LIMIT 1;"

Dump CSV for 1 contacts [y/N]? y
...
...05/21/2021,...
```

**Comment by leplatrem** [comment]
Indeed, the `Date` field on the main table is the only datetime object that needs to be casted to a date:


| Field                        | CTMS     | Acoustic                              |
|------------------------------|----------|---------------------------------------|
| main.create_timestamp        | datetime | date                                  |
| main.fxa_created_date        | string   | date (converted to date during sync)✅ |
| main.amo_last_login          | date     | date✅                                 |
| newsletter.create_timestamp  | datetime | text                                  |
| newsletter.update_timestamp  | datetime | text                                  |
| waitlist.create_timestamp    | datetime | timestamp✅                            |
| waitlist.update_timestamp    | datetime | timestamp✅                            |
| product.created              | datetime | timestamp✅                            |
| product.changed              | datetime | timestamp✅                            |
| product.start                | datetime | timestamp✅                            |
| product.current_period_start | datetime | timestamp✅                            |
| product.current_period_end   | datetime | timestamp✅                            |
| product.ended_at             | datetime | timestamp✅                            |
| product.canceled_at          | datetime | timestamp✅                            |
